### ISSUE TITLE
Support F-Droid

### ISSUE THREAD

**Issue by alterechtschreibung** [konklone/congress-android#545]
@konklone discusses publishing to [F-Droid](https://f-droid.org/) in [this discussion thread](http://f-droid.org/forums/topic/congress/):

```
In order to support F-Droid, I will need to:

* make it so if analytics is disabled through a configuration flag, this also activates graceful handling of the Google Analytics JAR being missing entirely.
* also, if analytics is disabled, do not include a menu option that goes to the Settings activity in the main screen.
* write a build script that does this work as part of the fdroid build process - and in general, automate as much of [the manual](https://f-droid.org/manual/) as possible.
```

I haven't yet firmly decided to do this - it is a non-trivial amount of work. However, if it is done, it'll be done in a manner that doesn't require maintaining a separate branch.

Other requirements:
- Deal with an API key that I don't want to commit to source control
- Other values in `keys.xml`, like our contact email, debug flags, etc.

**Comment by pizzamaker** [comment]
+1

**Comment by strugee** [comment]
@konklone why did this get closed?

**Comment by konklone** [comment]
@strugee The app is being transferred from the Sunlight Foundation to me personally, to manage updates in my (very limited) spare time. 

So, I went and closed most of the issues in the repository, and am going to be focused on slimming the app down to something that can a) withstand the forced migration from the sunsetting Sunlight Congress API to the Pro Publica API, and b) I stand a chance of being able to personally maintain.

That means focusing on as few channels as possible, so I'm limiting this to Google Play. This includes removing code and support for other already established non-Google channels of publication, such as Amazon, which I'm tracking in #654.
