### ISSUE TITLE
"Coming Up" bill detail can show very long list of activity

### ISSUE THREAD

**Issue by dcloud** [konklone/congress-android#643]
Per feedback from a user, this list can be long and annoying. Consider adding a way to limit the number of items that show up on a summary page.

![screenshot_2015-01-26-10-51-23](https://cloud.githubusercontent.com/assets/279327/5902773/480e440c-a54b-11e4-976c-d0bf307e67e8.png)

**Comment by konklone** [comment]
That should never be like that. There must be a bug somewhere in here, or in a calling function:

https://github.com/sunlightlabs/congress/blob/master/tasks/utils.rb#L567-L589

That code takes care of flushing previous "upcoming" notices, since they shouldn't accumulate like this.
