### ISSUE TITLE
Notifications go to app home screen rather than one specific to what notification is on

### ISSUE THREAD

**Issue by dcloud** [konklone/congress-android#644]
User reported:

> When I tap on a subscription notification it takes me to the app home screen and not the notification. E.g. I am notified of updates from the Senate, but when I tap the notification I go to the main Capitol screen.

Not sure if this is a bug or how the app chooses to handle notifications.

**Comment by konklone** [comment]
See if you can find out what kind of updates from the Senate the user means. This is unusual behavior that I wouldn't expect to see without a code regression of some kind. 

You could also see if the person's willing to send a bug report. In Android 4.X, you can turn on a developer setting that lets you use a button shortcut (Power + Vol Up + Vol Down) to capture logs and send device info, in a big .txt file, to whoever you want.

In Android 5.X, you can turn on a developer setting that adds the bug report option to the power menu:

![screenshot_2015-01-26-11-32-06](https://cloud.githubusercontent.com/assets/4592/5903458/cbd5f20e-a54f-11e4-9064-66a3b34daa7d.png)
