### ISSUE TITLE
Document new resource strings

### ISSUE THREAD

**Issue by divergentdave** [konklone/congress-android#714]
The new resource [`R.string.propublica_api_endpoint`](https://github.com/konklone/congress-android/commit/d9598c75e2d212ea7b30cc9809f294fc4c658383#diff-3fd0369cea2c4d342cb5f91291428435R45) should be documented in the README or added to `keys.xml.example`. I haven't checked if there are any other missing values.

(This issue was brought to you by [firstrunci](https://github.com/divergentdave/firstrunci) :D)

**Comment by konklone** [comment]
Thanks for reporting this. Done in 86c8289.
